import React, { useState } from 'react';

const BattleIdInput = ({ onBattleIdSubmit }) => {
    const [id, setId] = useState('');

    const handleSubmit = (e) => {
        e.preventDefault();
        if (id.trim()) {
            onBattleIdSubmit(id.trim());
        }
    };

    return (
        <div className="bg-gray-900 text-white min-h-screen flex flex-col justify-center items-center p-4">
            <div className="bg-gray-800 p-8 rounded-lg shadow-2xl max-w-md w-full">
                <h1 className="text-3xl font-bold text-indigo-400 mb-4 text-center">Battle Simulator</h1>
                <p className="text-gray-400 mb-6 text-center">To start, please enter a Battle ID generated by the Trainer Manager app.</p>
                <form onSubmit={handleSubmit} className="flex flex-col gap-4">
                    <input
                        type="text"
                        value={id}
                        onChange={(e) => setId(e.target.value)}
                        placeholder="Enter Battle ID..."
                        className="w-full bg-gray-900 p-3 rounded-md border border-gray-600 focus:ring-2 focus:ring-indigo-500 focus:outline-none"
                    />
                    <button type="submit" className="w-full bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-3 px-4 rounded-md transition-colors">
                        Load Battle
                    </button>
                </form>
            </div>
        </div>
    );
};

export default BattleIdInput;