// This file is auto-generated by generateFormsScript.js. Do not edit manually.

export const officialFormsData = {
  "venusaur": [
    {
      "formName": "venusaur-mega",
      "changeMethod": "BATTLE",
      "triggerItem": "Venusaurite",
      "data": {
        "speciesName": "venusaur-mega",
        "name": "Venusaur Mega",
        "types": [
          "grass",
          "poison"
        ],
        "baseStats": {
          "hp": 80,
          "attack": 100,
          "defense": 123,
          "special-attack": 122,
          "special-defense": 120,
          "speed": 80
        },
        "ability": "thick-fat",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10033.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10033.png"
        }
      }
    }
  ],
  "charizard": [
    {
      "formName": "charizard-mega-x",
      "changeMethod": "BATTLE",
      "triggerItem": "Charizardite X",
      "data": {
        "speciesName": "charizard-mega-x",
        "name": "Charizard Mega X",
        "types": [
          "fire",
          "dragon"
        ],
        "baseStats": {
          "hp": 78,
          "attack": 130,
          "defense": 111,
          "special-attack": 130,
          "special-defense": 85,
          "speed": 100
        },
        "ability": "tough-claws",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10034.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10034.png"
        }
      }
    },
    {
      "formName": "charizard-mega-y",
      "changeMethod": "BATTLE",
      "triggerItem": "Charizardite Y",
      "data": {
        "speciesName": "charizard-mega-y",
        "name": "Charizard Mega Y",
        "types": [
          "fire",
          "flying"
        ],
        "baseStats": {
          "hp": 78,
          "attack": 104,
          "defense": 78,
          "special-attack": 159,
          "special-defense": 115,
          "speed": 100
        },
        "ability": "drought",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10035.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10035.png"
        }
      }
    }
  ],
  "blastoise": [
    {
      "formName": "blastoise-mega",
      "changeMethod": "BATTLE",
      "triggerItem": "Blastoisinite",
      "data": {
        "speciesName": "blastoise-mega",
        "name": "Blastoise Mega",
        "types": [
          "water"
        ],
        "baseStats": {
          "hp": 79,
          "attack": 103,
          "defense": 120,
          "special-attack": 135,
          "special-defense": 115,
          "speed": 78
        },
        "ability": "mega-launcher",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10036.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10036.png"
        }
      }
    }
  ],
  "alakazam": [
    {
      "formName": "alakazam-mega",
      "changeMethod": "BATTLE",
      "triggerItem": "Alakazite",
      "data": {
        "speciesName": "alakazam-mega",
        "name": "Alakazam Mega",
        "types": [
          "psychic"
        ],
        "baseStats": {
          "hp": 55,
          "attack": 50,
          "defense": 65,
          "special-attack": 175,
          "special-defense": 105,
          "speed": 150
        },
        "ability": "trace",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10037.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10037.png"
        }
      }
    }
  ],
  "gengar": [
    {
      "formName": "gengar-mega",
      "changeMethod": "BATTLE",
      "triggerItem": "Gengarite",
      "data": {
        "speciesName": "gengar-mega",
        "name": "Gengar Mega",
        "types": [
          "ghost",
          "poison"
        ],
        "baseStats": {
          "hp": 60,
          "attack": 65,
          "defense": 80,
          "special-attack": 170,
          "special-defense": 95,
          "speed": 130
        },
        "ability": "shadow-tag",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10038.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10038.png"
        }
      }
    }
  ],
  "kangaskhan": [
    {
      "formName": "kangaskhan-mega",
      "changeMethod": "BATTLE",
      "triggerItem": "Kangaskhanite",
      "data": {
        "speciesName": "kangaskhan-mega",
        "name": "Kangaskhan Mega",
        "types": [
          "normal"
        ],
        "baseStats": {
          "hp": 105,
          "attack": 125,
          "defense": 100,
          "special-attack": 60,
          "special-defense": 100,
          "speed": 100
        },
        "ability": "parental-bond",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10039.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10039.png"
        }
      }
    }
  ],
  "pinsir": [
    {
      "formName": "pinsir-mega",
      "changeMethod": "BATTLE",
      "triggerItem": "Pinsirite",
      "data": {
        "speciesName": "pinsir-mega",
        "name": "Pinsir Mega",
        "types": [
          "bug",
          "flying"
        ],
        "baseStats": {
          "hp": 65,
          "attack": 155,
          "defense": 120,
          "special-attack": 65,
          "special-defense": 90,
          "speed": 105
        },
        "ability": "aerilate",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10040.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10040.png"
        }
      }
    }
  ],
  "gyarados": [
    {
      "formName": "gyarados-mega",
      "changeMethod": "BATTLE",
      "triggerItem": "Gyaradosite",
      "data": {
        "speciesName": "gyarados-mega",
        "name": "Gyarados Mega",
        "types": [
          "water",
          "dark"
        ],
        "baseStats": {
          "hp": 95,
          "attack": 155,
          "defense": 109,
          "special-attack": 70,
          "special-defense": 130,
          "speed": 81
        },
        "ability": "mold-breaker",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10041.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10041.png"
        }
      }
    }
  ],
  "aerodactyl": [
    {
      "formName": "aerodactyl-mega",
      "changeMethod": "BATTLE",
      "triggerItem": "Aerodactylite",
      "data": {
        "speciesName": "aerodactyl-mega",
        "name": "Aerodactyl Mega",
        "types": [
          "rock",
          "flying"
        ],
        "baseStats": {
          "hp": 80,
          "attack": 135,
          "defense": 85,
          "special-attack": 70,
          "special-defense": 95,
          "speed": 150
        },
        "ability": "tough-claws",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10042.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10042.png"
        }
      }
    }
  ],
  "mewtwo": [
    {
      "formName": "mewtwo-mega-x",
      "changeMethod": "BATTLE",
      "triggerItem": "Mewtwonite X",
      "data": {
        "speciesName": "mewtwo-mega-x",
        "name": "Mewtwo Mega X",
        "types": [
          "psychic",
          "fighting"
        ],
        "baseStats": {
          "hp": 106,
          "attack": 190,
          "defense": 100,
          "special-attack": 154,
          "special-defense": 100,
          "speed": 130
        },
        "ability": "steadfast",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10043.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10043.png"
        }
      }
    },
    {
      "formName": "mewtwo-mega-y",
      "changeMethod": "BATTLE",
      "triggerItem": "Mewtwonite Y",
      "data": {
        "speciesName": "mewtwo-mega-y",
        "name": "Mewtwo Mega Y",
        "types": [
          "psychic"
        ],
        "baseStats": {
          "hp": 106,
          "attack": 150,
          "defense": 70,
          "special-attack": 194,
          "special-defense": 120,
          "speed": 140
        },
        "ability": "insomnia",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10044.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10044.png"
        }
      }
    }
  ],
  "ampharos": [
    {
      "formName": "ampharos-mega",
      "changeMethod": "BATTLE",
      "triggerItem": "Ampharosite",
      "data": {
        "speciesName": "ampharos-mega",
        "name": "Ampharos Mega",
        "types": [
          "electric",
          "dragon"
        ],
        "baseStats": {
          "hp": 90,
          "attack": 95,
          "defense": 105,
          "special-attack": 165,
          "special-defense": 110,
          "speed": 45
        },
        "ability": "mold-breaker",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10045.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10045.png"
        }
      }
    }
  ],
  "scizor": [
    {
      "formName": "scizor-mega",
      "changeMethod": "BATTLE",
      "triggerItem": "Scizorite",
      "data": {
        "speciesName": "scizor-mega",
        "name": "Scizor Mega",
        "types": [
          "bug",
          "steel"
        ],
        "baseStats": {
          "hp": 70,
          "attack": 150,
          "defense": 140,
          "special-attack": 65,
          "special-defense": 100,
          "speed": 75
        },
        "ability": "technician",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10046.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10046.png"
        }
      }
    }
  ],
  "heracross": [
    {
      "formName": "heracross-mega",
      "changeMethod": "BATTLE",
      "triggerItem": "Heracronite",
      "data": {
        "speciesName": "heracross-mega",
        "name": "Heracross Mega",
        "types": [
          "bug",
          "fighting"
        ],
        "baseStats": {
          "hp": 80,
          "attack": 185,
          "defense": 115,
          "special-attack": 40,
          "special-defense": 105,
          "speed": 75
        },
        "ability": "skill-link",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10047.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10047.png"
        }
      }
    }
  ],
  "houndoom": [
    {
      "formName": "houndoom-mega",
      "changeMethod": "BATTLE",
      "triggerItem": "Houndoominite",
      "data": {
        "speciesName": "houndoom-mega",
        "name": "Houndoom Mega",
        "types": [
          "dark",
          "fire"
        ],
        "baseStats": {
          "hp": 75,
          "attack": 90,
          "defense": 90,
          "special-attack": 140,
          "special-defense": 90,
          "speed": 115
        },
        "ability": "solar-power",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10048.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10048.png"
        }
      }
    }
  ],
  "tyranitar": [
    {
      "formName": "tyranitar-mega",
      "changeMethod": "BATTLE",
      "triggerItem": "Tyranitarite",
      "data": {
        "speciesName": "tyranitar-mega",
        "name": "Tyranitar Mega",
        "types": [
          "rock",
          "dark"
        ],
        "baseStats": {
          "hp": 100,
          "attack": 164,
          "defense": 150,
          "special-attack": 95,
          "special-defense": 120,
          "speed": 71
        },
        "ability": "sand-stream",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10049.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10049.png"
        }
      }
    }
  ],
  "blaziken": [
    {
      "formName": "blaziken-mega",
      "changeMethod": "BATTLE",
      "triggerItem": "Blazikenite",
      "data": {
        "speciesName": "blaziken-mega",
        "name": "Blaziken Mega",
        "types": [
          "fire",
          "fighting"
        ],
        "baseStats": {
          "hp": 80,
          "attack": 160,
          "defense": 80,
          "special-attack": 130,
          "special-defense": 80,
          "speed": 100
        },
        "ability": "speed-boost",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10050.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10050.png"
        }
      }
    }
  ],
  "gardevoir": [
    {
      "formName": "gardevoir-mega",
      "changeMethod": "BATTLE",
      "triggerItem": "Gardevoirite",
      "data": {
        "speciesName": "gardevoir-mega",
        "name": "Gardevoir Mega",
        "types": [
          "psychic",
          "fairy"
        ],
        "baseStats": {
          "hp": 68,
          "attack": 85,
          "defense": 65,
          "special-attack": 165,
          "special-defense": 135,
          "speed": 100
        },
        "ability": "pixilate",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10051.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10051.png"
        }
      }
    }
  ],
  "mawile": [
    {
      "formName": "mawile-mega",
      "changeMethod": "BATTLE",
      "triggerItem": "Mawilite",
      "data": {
        "speciesName": "mawile-mega",
        "name": "Mawile Mega",
        "types": [
          "steel",
          "fairy"
        ],
        "baseStats": {
          "hp": 50,
          "attack": 105,
          "defense": 125,
          "special-attack": 55,
          "special-defense": 95,
          "speed": 50
        },
        "ability": "huge-power",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10052.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10052.png"
        }
      }
    }
  ],
  "aggron": [
    {
      "formName": "aggron-mega",
      "changeMethod": "BATTLE",
      "triggerItem": "Aggronite",
      "data": {
        "speciesName": "aggron-mega",
        "name": "Aggron Mega",
        "types": [
          "steel"
        ],
        "baseStats": {
          "hp": 70,
          "attack": 140,
          "defense": 230,
          "special-attack": 60,
          "special-defense": 80,
          "speed": 50
        },
        "ability": "filter",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10053.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10053.png"
        }
      }
    }
  ],
  "medicham": [
    {
      "formName": "medicham-mega",
      "changeMethod": "BATTLE",
      "triggerItem": "Medichamite",
      "data": {
        "speciesName": "medicham-mega",
        "name": "Medicham Mega",
        "types": [
          "fighting",
          "psychic"
        ],
        "baseStats": {
          "hp": 60,
          "attack": 100,
          "defense": 85,
          "special-attack": 80,
          "special-defense": 85,
          "speed": 100
        },
        "ability": "pure-power",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10054.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10054.png"
        }
      }
    }
  ],
  "manectric": [
    {
      "formName": "manectric-mega",
      "changeMethod": "BATTLE",
      "triggerItem": "Manectite",
      "data": {
        "speciesName": "manectric-mega",
        "name": "Manectric Mega",
        "types": [
          "electric"
        ],
        "baseStats": {
          "hp": 70,
          "attack": 75,
          "defense": 80,
          "special-attack": 135,
          "special-defense": 80,
          "speed": 135
        },
        "ability": "intimidate",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10055.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10055.png"
        }
      }
    }
  ],
  "banette": [
    {
      "formName": "banette-mega",
      "changeMethod": "BATTLE",
      "triggerItem": "Banettite",
      "data": {
        "speciesName": "banette-mega",
        "name": "Banette Mega",
        "types": [
          "ghost"
        ],
        "baseStats": {
          "hp": 64,
          "attack": 165,
          "defense": 75,
          "special-attack": 93,
          "special-defense": 83,
          "speed": 75
        },
        "ability": "prankster",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10056.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10056.png"
        }
      }
    }
  ],
  "absol": [
    {
      "formName": "absol-mega",
      "changeMethod": "BATTLE",
      "triggerItem": "Absolite",
      "data": {
        "speciesName": "absol-mega",
        "name": "Absol Mega",
        "types": [
          "dark"
        ],
        "baseStats": {
          "hp": 65,
          "attack": 150,
          "defense": 60,
          "special-attack": 115,
          "special-defense": 60,
          "speed": 115
        },
        "ability": "magic-bounce",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10057.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10057.png"
        }
      }
    }
  ],
  "garchomp": [
    {
      "formName": "garchomp-mega",
      "changeMethod": "BATTLE",
      "triggerItem": "Garchompite",
      "data": {
        "speciesName": "garchomp-mega",
        "name": "Garchomp Mega",
        "types": [
          "dragon",
          "ground"
        ],
        "baseStats": {
          "hp": 108,
          "attack": 170,
          "defense": 115,
          "special-attack": 120,
          "special-defense": 95,
          "speed": 92
        },
        "ability": "sand-force",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10058.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10058.png"
        }
      }
    }
  ],
  "lucario": [
    {
      "formName": "lucario-mega",
      "changeMethod": "BATTLE",
      "triggerItem": "Lucarionite",
      "data": {
        "speciesName": "lucario-mega",
        "name": "Lucario Mega",
        "types": [
          "fighting",
          "steel"
        ],
        "baseStats": {
          "hp": 70,
          "attack": 145,
          "defense": 88,
          "special-attack": 140,
          "special-defense": 70,
          "speed": 112
        },
        "ability": "adaptability",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10059.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10059.png"
        }
      }
    }
  ],
  "abomasnow": [
    {
      "formName": "abomasnow-mega",
      "changeMethod": "BATTLE",
      "triggerItem": "Abomasite",
      "data": {
        "speciesName": "abomasnow-mega",
        "name": "Abomasnow Mega",
        "types": [
          "grass",
          "ice"
        ],
        "baseStats": {
          "hp": 90,
          "attack": 132,
          "defense": 105,
          "special-attack": 132,
          "special-defense": 105,
          "speed": 30
        },
        "ability": "snow-warning",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10060.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10060.png"
        }
      }
    }
  ],
  "kyogre": [
    {
      "formName": "kyogre-primal",
      "changeMethod": "BATTLE",
      "triggerItem": "Blue Orb",
      "data": {
        "speciesName": "kyogre-primal",
        "name": "Kyogre Primal",
        "types": [
          "water"
        ],
        "baseStats": {
          "hp": 100,
          "attack": 150,
          "defense": 90,
          "special-attack": 180,
          "special-defense": 160,
          "speed": 90
        },
        "ability": "primordial-sea",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10077.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10077.png"
        }
      }
    }
  ],
  "groudon": [
    {
      "formName": "groudon-primal",
      "changeMethod": "BATTLE",
      "triggerItem": "Red Orb",
      "data": {
        "speciesName": "groudon-primal",
        "name": "Groudon Primal",
        "types": [
          "ground",
          "fire"
        ],
        "baseStats": {
          "hp": 100,
          "attack": 180,
          "defense": 160,
          "special-attack": 150,
          "special-defense": 90,
          "speed": 90
        },
        "ability": "desolate-land",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10078.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10078.png"
        }
      }
    }
  ],
  "rayquaza": [
    {
      "formName": "rayquaza-mega",
      "changeMethod": "BATTLE",
      "triggerMove": "Dragon Ascent",
      "data": {
        "speciesName": "rayquaza-mega",
        "name": "Rayquaza Mega",
        "types": [
          "dragon",
          "flying"
        ],
        "baseStats": {
          "hp": 105,
          "attack": 180,
          "defense": 100,
          "special-attack": 180,
          "special-defense": 100,
          "speed": 115
        },
        "ability": "delta-stream",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10079.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10079.png"
        }
      }
    }
  ],
  "meloetta": [
    {
      "formName": "meloetta-pirouette",
      "apiDataSource": "meloetta-pirouette",
      "changeMethod": "BATTLE",
      "triggerMove": "Relic Song",
      "data": {
        "speciesName": "meloetta-pirouette",
        "name": "Meloetta Pirouette",
        "types": [
          "normal",
          "fighting"
        ],
        "baseStats": {
          "hp": 100,
          "attack": 128,
          "defense": 90,
          "special-attack": 77,
          "special-defense": 77,
          "speed": 128
        },
        "ability": "serene-grace",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10018.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/648-pirouette.png"
        }
      }
    }
  ],
  "aegislash": [
    {
      "formName": "aegislash-blade",
      "apiDataSource": "aegislash-blade",
      "changeMethod": "BATTLE",
      "triggerAbility": "stance-change",
      "data": {
        "speciesName": "aegislash-blade",
        "name": "Aegislash Blade",
        "types": [
          "steel",
          "ghost"
        ],
        "baseStats": {
          "hp": 60,
          "attack": 140,
          "defense": 50,
          "special-attack": 140,
          "special-defense": 50,
          "speed": 60
        },
        "ability": "stance-change",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10026.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10026.png"
        }
      }
    }
  ],
  "darmanitan": [
    {
      "formName": "darmanitan-zen",
      "apiDataSource": "darmanitan-zen",
      "changeMethod": "BATTLE",
      "triggerAbility": "zen-mode",
      "triggerCondition": "HP_LT_50",
      "data": {
        "speciesName": "darmanitan-zen",
        "name": "Darmanitan Zen",
        "types": [
          "fire",
          "psychic"
        ],
        "baseStats": {
          "hp": 105,
          "attack": 30,
          "defense": 105,
          "special-attack": 140,
          "special-defense": 105,
          "speed": 55
        },
        "ability": "zen-mode",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10017.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/555-zen.png"
        }
      }
    },
    {
      "formName": "darmanitan-galar-zen",
      "apiDataSource": "darmanitan-galar-zen",
      "changeMethod": "BATTLE",
      "triggerAbility": "zen-mode",
      "triggerCondition": "HP_LT_50",
      "isGalarian": true,
      "data": {
        "speciesName": "darmanitan-galar-zen",
        "name": "Darmanitan Galar Zen",
        "types": [
          "ice",
          "fire"
        ],
        "baseStats": {
          "hp": 105,
          "attack": 160,
          "defense": 55,
          "special-attack": 30,
          "special-defense": 55,
          "speed": 135
        },
        "ability": "zen-mode",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10178.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10178.png"
        }
      }
    }
  ],
  "zygarde": [
    {
      "formName": "zygarde-complete",
      "apiDataSource": "zygarde-complete",
      "changeMethod": "BATTLE",
      "triggerAbility": "power-construct",
      "triggerCondition": "HP_LT_50",
      "data": {
        "speciesName": "zygarde-complete",
        "name": "Zygarde Complete",
        "types": [
          "dragon",
          "ground"
        ],
        "baseStats": {
          "hp": 216,
          "attack": 100,
          "defense": 121,
          "special-attack": 91,
          "special-defense": 95,
          "speed": 85
        },
        "ability": "power-construct",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10120.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10120.png"
        }
      }
    }
  ],
  "wishiwashi": [
    {
      "formName": "wishiwashi-school",
      "apiDataSource": "wishiwashi-school",
      "changeMethod": "BATTLE",
      "triggerAbility": "schooling",
      "triggerCondition": "HP_GT_25",
      "data": {
        "speciesName": "wishiwashi-school",
        "name": "Wishiwashi School",
        "types": [
          "water"
        ],
        "baseStats": {
          "hp": 45,
          "attack": 140,
          "defense": 130,
          "special-attack": 140,
          "special-defense": 135,
          "speed": 30
        },
        "ability": "schooling",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10127.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10127.png"
        }
      }
    }
  ],
  "minior": [
    {
      "formName": "minior-red",
      "apiDataSource": "minior-red",
      "changeMethod": "BATTLE",
      "triggerAbility": "shields-down",
      "triggerCondition": "HP_LT_50",
      "data": {
        "speciesName": "minior-red",
        "name": "Minior Red",
        "types": [
          "rock",
          "flying"
        ],
        "baseStats": {
          "hp": 60,
          "attack": 100,
          "defense": 60,
          "special-attack": 100,
          "special-defense": 60,
          "speed": 120
        },
        "ability": "shields-down",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10136.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10136.png"
        }
      }
    }
  ],
  "mimikyu": [
    {
      "formName": "mimikyu-busted",
      "apiDataSource": "mimikyu-busted",
      "changeMethod": "BATTLE",
      "triggerAbility": "disguise",
      "triggerCondition": "ON_DAMAGE",
      "data": {
        "speciesName": "mimikyu-busted",
        "name": "Mimikyu Busted",
        "types": [
          "ghost",
          "fairy"
        ],
        "baseStats": {
          "hp": 55,
          "attack": 90,
          "defense": 80,
          "special-attack": 50,
          "special-defense": 105,
          "speed": 96
        },
        "ability": "disguise",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10143.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10143.png"
        }
      }
    }
  ],
  "eiscue": [
    {
      "formName": "eiscue-noice",
      "apiDataSource": "eiscue-noice",
      "changeMethod": "BATTLE",
      "triggerAbility": "ice-face",
      "triggerCondition": "ON_PHYSICAL_DAMAGE",
      "data": {
        "speciesName": "eiscue-noice",
        "name": "Eiscue Noice",
        "types": [
          "ice"
        ],
        "baseStats": {
          "hp": 75,
          "attack": 80,
          "defense": 70,
          "special-attack": 65,
          "special-defense": 50,
          "speed": 130
        },
        "ability": "ice-face",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10185.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10185.png"
        }
      }
    }
  ],
  "morpeko": [
    {
      "formName": "morpeko-hangry",
      "apiDataSource": "morpeko-hangry",
      "changeMethod": "BATTLE",
      "triggerAbility": "hunger-switch",
      "triggerCondition": "END_OF_TURN",
      "data": {
        "speciesName": "morpeko-hangry",
        "name": "Morpeko Hangry",
        "types": [
          "electric",
          "dark"
        ],
        "baseStats": {
          "hp": 58,
          "attack": 95,
          "defense": 58,
          "special-attack": 70,
          "special-defense": 58,
          "speed": 97
        },
        "ability": "hunger-switch",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10187.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10187.png"
        }
      }
    }
  ],
  "castform": [
    {
      "formName": "castform-sunny",
      "changeMethod": "BATTLE",
      "triggerAbility": "forecast",
      "triggerCondition": "WEATHER_SUN",
      "data": {
        "speciesName": "castform-sunny",
        "name": "Castform Sunny",
        "types": [
          "fire"
        ],
        "baseStats": {
          "hp": 70,
          "attack": 70,
          "defense": 70,
          "special-attack": 70,
          "special-defense": 70,
          "speed": 70
        },
        "ability": "forecast",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10013.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10013.png"
        }
      }
    },
    {
      "formName": "castform-rainy",
      "changeMethod": "BATTLE",
      "triggerAbility": "forecast",
      "triggerCondition": "WEATHER_RAIN",
      "data": {
        "speciesName": "castform-rainy",
        "name": "Castform Rainy",
        "types": [
          "water"
        ],
        "baseStats": {
          "hp": 70,
          "attack": 70,
          "defense": 70,
          "special-attack": 70,
          "special-defense": 70,
          "speed": 70
        },
        "ability": "forecast",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10014.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10014.png"
        }
      }
    },
    {
      "formName": "castform-snowy",
      "changeMethod": "BATTLE",
      "triggerAbility": "forecast",
      "triggerCondition": "WEATHER_SNOW",
      "data": {
        "speciesName": "castform-snowy",
        "name": "Castform Snowy",
        "types": [
          "ice"
        ],
        "baseStats": {
          "hp": 70,
          "attack": 70,
          "defense": 70,
          "special-attack": 70,
          "special-defense": 70,
          "speed": 70
        },
        "ability": "forecast",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10015.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10015.png"
        }
      }
    }
  ],
  "cherrim": [
    {
      "formName": "cherrim-sunshine",
      "apiDataSource": "cherrim",
      "changeMethod": "BATTLE",
      "triggerAbility": "flower-gift",
      "triggerCondition": "WEATHER_SUN",
      "data": {
        "speciesName": "cherrim-sunshine",
        "name": "Cherrim Sunshine",
        "types": [
          "grass"
        ],
        "baseStats": {
          "hp": 70,
          "attack": 60,
          "defense": 70,
          "special-attack": 87,
          "special-defense": 78,
          "speed": 85
        },
        "ability": "flower-gift",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/421.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/421.png"
        }
      }
    }
  ],
  "zacian": [
    {
      "formName": "zacian-crowned",
      "changeMethod": "BATTLE",
      "triggerItem": "Rusted Sword",
      "data": {
        "speciesName": "zacian-crowned",
        "name": "Zacian Crowned",
        "types": [
          "fairy",
          "steel"
        ],
        "baseStats": {
          "hp": 92,
          "attack": 150,
          "defense": 115,
          "special-attack": 80,
          "special-defense": 115,
          "speed": 148
        },
        "ability": "intrepid-sword",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10188.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10188.png"
        }
      }
    }
  ],
  "zamazenta": [
    {
      "formName": "zamazenta-crowned",
      "changeMethod": "BATTLE",
      "triggerItem": "Rusted Shield",
      "data": {
        "speciesName": "zamazenta-crowned",
        "name": "Zamazenta Crowned",
        "types": [
          "fighting",
          "steel"
        ],
        "baseStats": {
          "hp": 92,
          "attack": 120,
          "defense": 140,
          "special-attack": 80,
          "special-defense": 140,
          "speed": 128
        },
        "ability": "dauntless-shield",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10189.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10189.png"
        }
      }
    }
  ],
  "arceus": [
    {
      "formName": "arceus-fighting",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Fist Plate",
      "apiDataSource": "arceus",
      "data": {
        "speciesName": "arceus-fighting",
        "name": "Arceus Fighting",
        "types": [
          "fighting"
        ],
        "baseStats": {
          "hp": 120,
          "attack": 120,
          "defense": 120,
          "special-attack": 120,
          "special-defense": 120,
          "speed": 120
        },
        "ability": "multitype",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/493-fighting.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/493-fighting.png"
        }
      }
    },
    {
      "formName": "arceus-flying",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Sky Plate",
      "apiDataSource": "arceus",
      "data": {
        "speciesName": "arceus-flying",
        "name": "Arceus Flying",
        "types": [
          "flying"
        ],
        "baseStats": {
          "hp": 120,
          "attack": 120,
          "defense": 120,
          "special-attack": 120,
          "special-defense": 120,
          "speed": 120
        },
        "ability": "multitype",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/493-flying.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/493-flying.png"
        }
      }
    },
    {
      "formName": "arceus-poison",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Toxic Plate",
      "apiDataSource": "arceus",
      "data": {
        "speciesName": "arceus-poison",
        "name": "Arceus Poison",
        "types": [
          "poison"
        ],
        "baseStats": {
          "hp": 120,
          "attack": 120,
          "defense": 120,
          "special-attack": 120,
          "special-defense": 120,
          "speed": 120
        },
        "ability": "multitype",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/493-poison.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/493-poison.png"
        }
      }
    },
    {
      "formName": "arceus-ground",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Earth Plate",
      "apiDataSource": "arceus",
      "data": {
        "speciesName": "arceus-ground",
        "name": "Arceus Ground",
        "types": [
          "ground"
        ],
        "baseStats": {
          "hp": 120,
          "attack": 120,
          "defense": 120,
          "special-attack": 120,
          "special-defense": 120,
          "speed": 120
        },
        "ability": "multitype",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/493-ground.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/493-ground.png"
        }
      }
    },
    {
      "formName": "arceus-rock",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Stone Plate",
      "apiDataSource": "arceus",
      "data": {
        "speciesName": "arceus-rock",
        "name": "Arceus Rock",
        "types": [
          "rock"
        ],
        "baseStats": {
          "hp": 120,
          "attack": 120,
          "defense": 120,
          "special-attack": 120,
          "special-defense": 120,
          "speed": 120
        },
        "ability": "multitype",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/493-rock.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/493-rock.png"
        }
      }
    },
    {
      "formName": "arceus-bug",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Insect Plate",
      "apiDataSource": "arceus",
      "data": {
        "speciesName": "arceus-bug",
        "name": "Arceus Bug",
        "types": [
          "bug"
        ],
        "baseStats": {
          "hp": 120,
          "attack": 120,
          "defense": 120,
          "special-attack": 120,
          "special-defense": 120,
          "speed": 120
        },
        "ability": "multitype",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/493-bug.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/493-bug.png"
        }
      }
    },
    {
      "formName": "arceus-ghost",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Spooky Plate",
      "apiDataSource": "arceus",
      "data": {
        "speciesName": "arceus-ghost",
        "name": "Arceus Ghost",
        "types": [
          "ghost"
        ],
        "baseStats": {
          "hp": 120,
          "attack": 120,
          "defense": 120,
          "special-attack": 120,
          "special-defense": 120,
          "speed": 120
        },
        "ability": "multitype",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/493-ghost.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/493-ghost.png"
        }
      }
    },
    {
      "formName": "arceus-steel",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Iron Plate",
      "apiDataSource": "arceus",
      "data": {
        "speciesName": "arceus-steel",
        "name": "Arceus Steel",
        "types": [
          "steel"
        ],
        "baseStats": {
          "hp": 120,
          "attack": 120,
          "defense": 120,
          "special-attack": 120,
          "special-defense": 120,
          "speed": 120
        },
        "ability": "multitype",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/493-steel.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/493-steel.png"
        }
      }
    },
    {
      "formName": "arceus-fire",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Flame Plate",
      "apiDataSource": "arceus",
      "data": {
        "speciesName": "arceus-fire",
        "name": "Arceus Fire",
        "types": [
          "fire"
        ],
        "baseStats": {
          "hp": 120,
          "attack": 120,
          "defense": 120,
          "special-attack": 120,
          "special-defense": 120,
          "speed": 120
        },
        "ability": "multitype",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/493-fire.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/493-fire.png"
        }
      }
    },
    {
      "formName": "arceus-water",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Splash Plate",
      "apiDataSource": "arceus",
      "data": {
        "speciesName": "arceus-water",
        "name": "Arceus Water",
        "types": [
          "water"
        ],
        "baseStats": {
          "hp": 120,
          "attack": 120,
          "defense": 120,
          "special-attack": 120,
          "special-defense": 120,
          "speed": 120
        },
        "ability": "multitype",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/493-water.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/493-water.png"
        }
      }
    },
    {
      "formName": "arceus-grass",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Meadow Plate",
      "apiDataSource": "arceus",
      "data": {
        "speciesName": "arceus-grass",
        "name": "Arceus Grass",
        "types": [
          "grass"
        ],
        "baseStats": {
          "hp": 120,
          "attack": 120,
          "defense": 120,
          "special-attack": 120,
          "special-defense": 120,
          "speed": 120
        },
        "ability": "multitype",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/493-grass.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/493-grass.png"
        }
      }
    },
    {
      "formName": "arceus-electric",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Zap Plate",
      "apiDataSource": "arceus",
      "data": {
        "speciesName": "arceus-electric",
        "name": "Arceus Electric",
        "types": [
          "electric"
        ],
        "baseStats": {
          "hp": 120,
          "attack": 120,
          "defense": 120,
          "special-attack": 120,
          "special-defense": 120,
          "speed": 120
        },
        "ability": "multitype",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/493-electric.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/493-electric.png"
        }
      }
    },
    {
      "formName": "arceus-psychic",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Mind Plate",
      "apiDataSource": "arceus",
      "data": {
        "speciesName": "arceus-psychic",
        "name": "Arceus Psychic",
        "types": [
          "psychic"
        ],
        "baseStats": {
          "hp": 120,
          "attack": 120,
          "defense": 120,
          "special-attack": 120,
          "special-defense": 120,
          "speed": 120
        },
        "ability": "multitype",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/493-psychic.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/493-psychic.png"
        }
      }
    },
    {
      "formName": "arceus-ice",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Icicle Plate",
      "apiDataSource": "arceus",
      "data": {
        "speciesName": "arceus-ice",
        "name": "Arceus Ice",
        "types": [
          "ice"
        ],
        "baseStats": {
          "hp": 120,
          "attack": 120,
          "defense": 120,
          "special-attack": 120,
          "special-defense": 120,
          "speed": 120
        },
        "ability": "multitype",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/493-ice.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/493-ice.png"
        }
      }
    },
    {
      "formName": "arceus-dragon",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Draco Plate",
      "apiDataSource": "arceus",
      "data": {
        "speciesName": "arceus-dragon",
        "name": "Arceus Dragon",
        "types": [
          "dragon"
        ],
        "baseStats": {
          "hp": 120,
          "attack": 120,
          "defense": 120,
          "special-attack": 120,
          "special-defense": 120,
          "speed": 120
        },
        "ability": "multitype",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/493-dragon.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/493-dragon.png"
        }
      }
    },
    {
      "formName": "arceus-dark",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Dread Plate",
      "apiDataSource": "arceus",
      "data": {
        "speciesName": "arceus-dark",
        "name": "Arceus Dark",
        "types": [
          "dark"
        ],
        "baseStats": {
          "hp": 120,
          "attack": 120,
          "defense": 120,
          "special-attack": 120,
          "special-defense": 120,
          "speed": 120
        },
        "ability": "multitype",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/493-dark.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/493-dark.png"
        }
      }
    },
    {
      "formName": "arceus-fairy",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Pixie Plate",
      "apiDataSource": "arceus",
      "data": {
        "speciesName": "arceus-fairy",
        "name": "Arceus Fairy",
        "types": [
          "fairy"
        ],
        "baseStats": {
          "hp": 120,
          "attack": 120,
          "defense": 120,
          "special-attack": 120,
          "special-defense": 120,
          "speed": 120
        },
        "ability": "multitype",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/493-fairy.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/493-fairy.png"
        }
      }
    }
  ],
  "silvally": [
    {
      "formName": "silvally-fighting",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Fighting Memory",
      "apiDataSource": "silvally",
      "data": {
        "speciesName": "silvally-fighting",
        "name": "Silvally Fighting",
        "types": [
          "fighting"
        ],
        "baseStats": {
          "hp": 95,
          "attack": 95,
          "defense": 95,
          "special-attack": 95,
          "special-defense": 95,
          "speed": 95
        },
        "ability": "rks-system",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/773-fighting.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/773-fighting.png"
        }
      }
    },
    {
      "formName": "silvally-flying",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Flying Memory",
      "apiDataSource": "silvally",
      "data": {
        "speciesName": "silvally-flying",
        "name": "Silvally Flying",
        "types": [
          "flying"
        ],
        "baseStats": {
          "hp": 95,
          "attack": 95,
          "defense": 95,
          "special-attack": 95,
          "special-defense": 95,
          "speed": 95
        },
        "ability": "rks-system",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/773-flying.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/773-flying.png"
        }
      }
    },
    {
      "formName": "silvally-poison",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Poison Memory",
      "apiDataSource": "silvally",
      "data": {
        "speciesName": "silvally-poison",
        "name": "Silvally Poison",
        "types": [
          "poison"
        ],
        "baseStats": {
          "hp": 95,
          "attack": 95,
          "defense": 95,
          "special-attack": 95,
          "special-defense": 95,
          "speed": 95
        },
        "ability": "rks-system",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/773-poison.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/773-poison.png"
        }
      }
    },
    {
      "formName": "silvally-ground",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Ground Memory",
      "apiDataSource": "silvally",
      "data": {
        "speciesName": "silvally-ground",
        "name": "Silvally Ground",
        "types": [
          "ground"
        ],
        "baseStats": {
          "hp": 95,
          "attack": 95,
          "defense": 95,
          "special-attack": 95,
          "special-defense": 95,
          "speed": 95
        },
        "ability": "rks-system",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/773-ground.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/773-ground.png"
        }
      }
    },
    {
      "formName": "silvally-rock",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Rock Memory",
      "apiDataSource": "silvally",
      "data": {
        "speciesName": "silvally-rock",
        "name": "Silvally Rock",
        "types": [
          "rock"
        ],
        "baseStats": {
          "hp": 95,
          "attack": 95,
          "defense": 95,
          "special-attack": 95,
          "special-defense": 95,
          "speed": 95
        },
        "ability": "rks-system",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/773-rock.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/773-rock.png"
        }
      }
    },
    {
      "formName": "silvally-bug",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Bug Memory",
      "apiDataSource": "silvally",
      "data": {
        "speciesName": "silvally-bug",
        "name": "Silvally Bug",
        "types": [
          "bug"
        ],
        "baseStats": {
          "hp": 95,
          "attack": 95,
          "defense": 95,
          "special-attack": 95,
          "special-defense": 95,
          "speed": 95
        },
        "ability": "rks-system",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/773-bug.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/773-bug.png"
        }
      }
    },
    {
      "formName": "silvally-ghost",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Ghost Memory",
      "apiDataSource": "silvally",
      "data": {
        "speciesName": "silvally-ghost",
        "name": "Silvally Ghost",
        "types": [
          "ghost"
        ],
        "baseStats": {
          "hp": 95,
          "attack": 95,
          "defense": 95,
          "special-attack": 95,
          "special-defense": 95,
          "speed": 95
        },
        "ability": "rks-system",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/773-ghost.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/773-ghost.png"
        }
      }
    },
    {
      "formName": "silvally-steel",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Steel Memory",
      "apiDataSource": "silvally",
      "data": {
        "speciesName": "silvally-steel",
        "name": "Silvally Steel",
        "types": [
          "steel"
        ],
        "baseStats": {
          "hp": 95,
          "attack": 95,
          "defense": 95,
          "special-attack": 95,
          "special-defense": 95,
          "speed": 95
        },
        "ability": "rks-system",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/773-steel.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/773-steel.png"
        }
      }
    },
    {
      "formName": "silvally-fire",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Fire Memory",
      "apiDataSource": "silvally",
      "data": {
        "speciesName": "silvally-fire",
        "name": "Silvally Fire",
        "types": [
          "fire"
        ],
        "baseStats": {
          "hp": 95,
          "attack": 95,
          "defense": 95,
          "special-attack": 95,
          "special-defense": 95,
          "speed": 95
        },
        "ability": "rks-system",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/773-fire.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/773-fire.png"
        }
      }
    },
    {
      "formName": "silvally-water",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Water Memory",
      "apiDataSource": "silvally",
      "data": {
        "speciesName": "silvally-water",
        "name": "Silvally Water",
        "types": [
          "water"
        ],
        "baseStats": {
          "hp": 95,
          "attack": 95,
          "defense": 95,
          "special-attack": 95,
          "special-defense": 95,
          "speed": 95
        },
        "ability": "rks-system",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/773-water.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/773-water.png"
        }
      }
    },
    {
      "formName": "silvally-grass",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Grass Memory",
      "apiDataSource": "silvally",
      "data": {
        "speciesName": "silvally-grass",
        "name": "Silvally Grass",
        "types": [
          "grass"
        ],
        "baseStats": {
          "hp": 95,
          "attack": 95,
          "defense": 95,
          "special-attack": 95,
          "special-defense": 95,
          "speed": 95
        },
        "ability": "rks-system",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/773-grass.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/773-grass.png"
        }
      }
    },
    {
      "formName": "silvally-electric",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Electric Memory",
      "apiDataSource": "silvally",
      "data": {
        "speciesName": "silvally-electric",
        "name": "Silvally Electric",
        "types": [
          "electric"
        ],
        "baseStats": {
          "hp": 95,
          "attack": 95,
          "defense": 95,
          "special-attack": 95,
          "special-defense": 95,
          "speed": 95
        },
        "ability": "rks-system",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/773-electric.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/773-electric.png"
        }
      }
    },
    {
      "formName": "silvally-psychic",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Psychic Memory",
      "apiDataSource": "silvally",
      "data": {
        "speciesName": "silvally-psychic",
        "name": "Silvally Psychic",
        "types": [
          "psychic"
        ],
        "baseStats": {
          "hp": 95,
          "attack": 95,
          "defense": 95,
          "special-attack": 95,
          "special-defense": 95,
          "speed": 95
        },
        "ability": "rks-system",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/773-psychic.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/773-psychic.png"
        }
      }
    },
    {
      "formName": "silvally-ice",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Ice Memory",
      "apiDataSource": "silvally",
      "data": {
        "speciesName": "silvally-ice",
        "name": "Silvally Ice",
        "types": [
          "ice"
        ],
        "baseStats": {
          "hp": 95,
          "attack": 95,
          "defense": 95,
          "special-attack": 95,
          "special-defense": 95,
          "speed": 95
        },
        "ability": "rks-system",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/773-ice.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/773-ice.png"
        }
      }
    },
    {
      "formName": "silvally-dragon",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Dragon Memory",
      "apiDataSource": "silvally",
      "data": {
        "speciesName": "silvally-dragon",
        "name": "Silvally Dragon",
        "types": [
          "dragon"
        ],
        "baseStats": {
          "hp": 95,
          "attack": 95,
          "defense": 95,
          "special-attack": 95,
          "special-defense": 95,
          "speed": 95
        },
        "ability": "rks-system",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/773-dragon.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/773-dragon.png"
        }
      }
    },
    {
      "formName": "silvally-dark",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Dark Memory",
      "apiDataSource": "silvally",
      "data": {
        "speciesName": "silvally-dark",
        "name": "Silvally Dark",
        "types": [
          "dark"
        ],
        "baseStats": {
          "hp": 95,
          "attack": 95,
          "defense": 95,
          "special-attack": 95,
          "special-defense": 95,
          "speed": 95
        },
        "ability": "rks-system",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/773-dark.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/773-dark.png"
        }
      }
    },
    {
      "formName": "silvally-fairy",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Fairy Memory",
      "apiDataSource": "silvally",
      "data": {
        "speciesName": "silvally-fairy",
        "name": "Silvally Fairy",
        "types": [
          "fairy"
        ],
        "baseStats": {
          "hp": 95,
          "attack": 95,
          "defense": 95,
          "special-attack": 95,
          "special-defense": 95,
          "speed": 95
        },
        "ability": "rks-system",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/773-fairy.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/773-fairy.png"
        }
      }
    }
  ],
  "genesect": [
    {
      "formName": "genesect-douse",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Douse Drive",
      "apiDataSource": "genesect",
      "data": {
        "speciesName": "genesect-douse",
        "name": "Genesect Douse",
        "types": [
          "bug",
          "steel"
        ],
        "baseStats": {
          "hp": 71,
          "attack": 120,
          "defense": 95,
          "special-attack": 120,
          "special-defense": 95,
          "speed": 99
        },
        "ability": "download",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/649-douse.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/649-douse.png"
        }
      }
    },
    {
      "formName": "genesect-shock",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Shock Drive",
      "apiDataSource": "genesect",
      "data": {
        "speciesName": "genesect-shock",
        "name": "Genesect Shock",
        "types": [
          "bug",
          "steel"
        ],
        "baseStats": {
          "hp": 71,
          "attack": 120,
          "defense": 95,
          "special-attack": 120,
          "special-defense": 95,
          "speed": 99
        },
        "ability": "download",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/649-shock.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/649-shock.png"
        }
      }
    },
    {
      "formName": "genesect-burn",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Burn Drive",
      "apiDataSource": "genesect",
      "data": {
        "speciesName": "genesect-burn",
        "name": "Genesect Burn",
        "types": [
          "bug",
          "steel"
        ],
        "baseStats": {
          "hp": 71,
          "attack": 120,
          "defense": 95,
          "special-attack": 120,
          "special-defense": 95,
          "speed": 99
        },
        "ability": "download",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/649-burn.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/649-burn.png"
        }
      }
    },
    {
      "formName": "genesect-chill",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Chill Drive",
      "apiDataSource": "genesect",
      "data": {
        "speciesName": "genesect-chill",
        "name": "Genesect Chill",
        "types": [
          "bug",
          "steel"
        ],
        "baseStats": {
          "hp": 71,
          "attack": 120,
          "defense": 95,
          "special-attack": 120,
          "special-defense": 95,
          "speed": 99
        },
        "ability": "download",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/649-chill.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/649-chill.png"
        }
      }
    }
  ],
  "giratina": [
    {
      "formName": "giratina-origin",
      "apiDataSource": "giratina-origin",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Griseous Orb",
      "data": {
        "speciesName": "giratina-origin",
        "name": "Giratina Origin",
        "types": [
          "ghost",
          "dragon"
        ],
        "baseStats": {
          "hp": 150,
          "attack": 120,
          "defense": 100,
          "special-attack": 120,
          "special-defense": 100,
          "speed": 90
        },
        "ability": "levitate",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10007.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/487-origin.png"
        }
      }
    }
  ],
  "dialga": [
    {
      "formName": "dialga-origin",
      "apiDataSource": "dialga-origin",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Adamant Crystal",
      "data": {
        "speciesName": "dialga-origin",
        "name": "Dialga Origin",
        "types": [
          "steel",
          "dragon"
        ],
        "baseStats": {
          "hp": 100,
          "attack": 100,
          "defense": 120,
          "special-attack": 150,
          "special-defense": 120,
          "speed": 90
        },
        "ability": "pressure",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10245.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10245.png"
        }
      }
    }
  ],
  "palkia": [
    {
      "formName": "palkia-origin",
      "apiDataSource": "palkia-origin",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Lustrous Globe",
      "data": {
        "speciesName": "palkia-origin",
        "name": "Palkia Origin",
        "types": [
          "water",
          "dragon"
        ],
        "baseStats": {
          "hp": 90,
          "attack": 100,
          "defense": 100,
          "special-attack": 150,
          "special-defense": 120,
          "speed": 120
        },
        "ability": "pressure",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10246.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10246.png"
        }
      }
    }
  ],
  "ogerpon": [
    {
      "formName": "ogerpon-wellspring-mask",
      "apiDataSource": "ogerpon-wellspring-mask",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Wellspring Mask",
      "data": {
        "speciesName": "ogerpon-wellspring-mask",
        "name": "Ogerpon Wellspring Mask",
        "types": [
          "grass",
          "water"
        ],
        "baseStats": {
          "hp": 80,
          "attack": 120,
          "defense": 84,
          "special-attack": 60,
          "special-defense": 96,
          "speed": 110
        },
        "ability": "water-absorb",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10273.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10273.png"
        }
      }
    },
    {
      "formName": "ogerpon-hearthflame-mask",
      "apiDataSource": "ogerpon-hearthflame-mask",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Hearthflame Mask",
      "data": {
        "speciesName": "ogerpon-hearthflame-mask",
        "name": "Ogerpon Hearthflame Mask",
        "types": [
          "grass",
          "fire"
        ],
        "baseStats": {
          "hp": 80,
          "attack": 120,
          "defense": 84,
          "special-attack": 60,
          "special-defense": 96,
          "speed": 110
        },
        "ability": "mold-breaker",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10274.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10274.png"
        }
      }
    },
    {
      "formName": "ogerpon-cornerstone-mask",
      "apiDataSource": "ogerpon-cornerstone-mask",
      "changeMethod": "ITEM_HOLD",
      "triggerItem": "Cornerstone Mask",
      "data": {
        "speciesName": "ogerpon-cornerstone-mask",
        "name": "Ogerpon Cornerstone Mask",
        "types": [
          "grass",
          "rock"
        ],
        "baseStats": {
          "hp": 80,
          "attack": 120,
          "defense": 84,
          "special-attack": 60,
          "special-defense": 96,
          "speed": 110
        },
        "ability": "sturdy",
        "sprites": {
          "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10275.png",
          "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10275.png"
        }
      }
    }
  ]
};